# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys

# Uncomment and configure the following if you need a database
#   depends_on:
#     db:
#       condition: service_healthy
# db:
#   image: postgres
#   restart: always
#   user: postgres
#   secrets:
#     - db-password
#   volumes:
#     - db-data:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_DB=example
#     - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#   expose:
#     - 5432
#   healthcheck:
#     test: ["CMD", "pg_isready"]
#     interval: 10s
#     timeout: 5s
#     retries: 5
#
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt